import "./globals.css";
import Header from "@/components/layouts/Header";
import { Roboto, Nunito } from "@next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const display = Nunito({
  subsets: ["latin"],
  weight: ["300", "500", "700"],
  variable: "--display-font",
});

const body = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700", "900"],
  variable: "--body-font",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${body.variable} font-display`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
